use serde::{Serialize,Deserialize};use std::{io::{BufRead,BufReader,Write},path::{Path,PathBuf},process::{Child,Command,Stdio},sync::{Arc,Mutex},time::{Duration,Instant}};use thiserror::Error;
#[derive(Debug,Clone,Serialize,Deserialize)]pub struct RuntimeInfo{pub executable:String,pub version:Option<String>,pub status:String,pub detail:Option<String>,pub protocol:Option<u32>,pub capabilities:Option<serde_json::Value>}
#[derive(Debug,Error)]pub enum RuntimeError{#[error("omp executable not found")]NotFound,#[error("omp is not executable: {0}")]NotExecutable(String),#[error("version probe failed: {0}")]Probe(String),#[error("unsupported omp version: {0}")]Unsupported(String),#[error("rpc handshake failed: {0}")]Handshake(String)}
pub fn resolve_executable(explicit:Option<&Path>)->Result<PathBuf,RuntimeError>{if let Some(p)=explicit{if p.is_file(){return Ok(p.to_path_buf())}return Err(RuntimeError::NotExecutable(p.display().to_string()))}if let Ok(path)=std::env::var("PATH"){for d in path.split(':'){let p=Path::new(d).join("omp");if p.is_file(){return Ok(p)}}}Err(RuntimeError::NotFound)}
pub fn probe(path:&Path)->Result<RuntimeInfo,RuntimeError>{let o=Command::new(path).arg("--version").output().map_err(|e|RuntimeError::Probe(e.to_string()))?;if !o.status.success(){return Err(RuntimeError::Probe(String::from_utf8_lossy(&o.stderr).trim().into()))}Ok(RuntimeInfo{executable:path.display().to_string(),version:Some(String::from_utf8_lossy(&o.stdout).trim().into()),status:"ready".into(),detail:None,protocol:None,capabilities:None})}
pub struct OmpProcess{pub child:Child,pub protocol:u32}
impl Drop for OmpProcess{fn drop(&mut self){let _=self.child.kill();let _=self.child.wait();}}
pub fn start_rpc(path:&Path,cwd:Option<&Path>)->Result<OmpProcess,RuntimeError>{let mut c=Command::new(path);c.args(["--mode","rpc"]).stdin(Stdio::piped()).stdout(Stdio::piped()).stderr(Stdio::piped());if let Some(d)=cwd{c.current_dir(d);}let mut child=c.spawn().map_err(|e|RuntimeError::Probe(format!("start rpc: {e}")))?;let i=child.stdin.as_mut().ok_or_else(||RuntimeError::Probe("rpc stdin unavailable".into()))?;writeln!(i,"{{\"id\":\"negotiate-protocol\",\"type\":\"negotiate_protocol\",\"protocolVersion\":2}}").map_err(|e|RuntimeError::Probe(e.to_string()))?;i.flush().ok();Ok(OmpProcess{child,protocol:2})}
pub fn handshake(path:&Path,cwd:Option<&Path>)->Result<RuntimeInfo,RuntimeError>{let mut p=start_rpc(path,cwd)?;let out=p.child.stdout.take().ok_or_else(||RuntimeError::Handshake("stdout unavailable".into()))?;let mut r=BufReader::new(out);let start=Instant::now();let mut line=String::new();while start.elapsed()<Duration::from_secs(8){line.clear();match r.read_line(&mut line){Ok(0)=>break,Ok(_)=>if let Ok(v)=serde_json::from_str::<serde_json::Value>(line.trim()){if v.get("type").and_then(|x|x.as_str())==Some("ready")||v.get("protocolVersion").is_some(){return Ok(RuntimeInfo{executable:path.display().to_string(),version:None,status:"ready".into(),detail:None,protocol:v.get("protocolVersion").and_then(|x|x.as_u64()).map(|x|x as u32).or(Some(2)),capabilities:Some(v)});}},Err(e)=>return Err(RuntimeError::Handshake(e.to_string()))}}Err(RuntimeError::Handshake("timeout waiting for ready".into()))}
#[derive(Debug,Clone,Serialize,Deserialize)]pub struct TaskSnapshot{pub task_id:String,pub status:String,pub seq:u64,pub messages:Vec<String>}
pub struct TaskManager{tasks:Arc<Mutex<std::collections::HashMap<String,TaskSnapshot>>>}
impl TaskManager{pub fn new()->Self{Self{tasks:Arc::new(Mutex::new(Default::default()))}}pub fn create(&self,id:String){self.tasks.lock().unwrap().insert(id.clone(),TaskSnapshot{task_id:id,status:"idle".into(),seq:0,messages:vec![]});}pub fn snapshot(&self,id:&str)->Option<TaskSnapshot>{self.tasks.lock().unwrap().get(id).cloned()}pub fn set_status(&self,id:&str,status:String){if let Some(t)=self.tasks.lock().unwrap().get_mut(id){t.status=status;t.seq+=1;}}}
#[cfg(test)]mod tests{use super::*;#[test]fn missing(){assert!(matches!(resolve_executable(Some(Path::new("/missing/omp"))),Err(RuntimeError::NotExecutable(_))))}#[test]fn tasks_isolate(){let m=TaskManager::new();m.create("a".into());m.create("b".into());m.set_status("a","running".into());assert_eq!(m.snapshot("b").unwrap().status,"idle");}}
