import {invoke} from '@tauri-apps/api/core';import type {HostError,TaskSnapshot,RuntimeInfo,ObserverInfo} from '../../../packages/host-contract/src';
import type {Project,TaskRecord,HistoryPage,GitStatus,GitDiff,TaskRoot} from '../../../packages/host-contract/src';
export const projects={list:()=>invoke<Project[]>('list_projects'),register:(name:string,trusted:boolean)=>invoke<Project|null>('register_project',{name,trusted}),update:(id:string,name:string,archived:boolean)=>invoke<void>('update_project',{id,name,archived})};
export const records={list:()=>invoke<TaskRecord[]>('task_records'),create:(projectId:string,title:string,mode:'shared'|'isolated'='shared')=>invoke<TaskRecord>('create_task',{projectId,title,mode}),update:(task:TaskRecord)=>invoke<TaskRecord>('update_task',{id:task.id,title:task.title,pinned:task.pinned,archived:task.archived}),relocate:(taskId:string,trusted:boolean)=>invoke<TaskRecord|null>('relocate_task',{taskId,trusted}),resume:(taskId:string)=>invoke<TaskSnapshot>('continue_task',{taskId}),history:(taskId:string,cursor:string|null)=>invoke<HistoryPage>('task_history',{taskId,cursor}),usage:(taskId:string)=>invoke<TaskSnapshot>('task_usage',{taskId}),gitStatus:(taskId:string,rootIndex:number)=>invoke<GitStatus>('task_git_status',{taskId,rootIndex}),gitDiff:(taskId:string,rootIndex:number,path:string,staged:boolean,untracked:boolean)=>invoke<GitDiff>('task_git_diff',{taskId,rootIndex,path,staged,untracked}),model:(taskId:string,provider:string,modelId:string)=>invoke<Record<string,unknown>>('select_task_model',{taskId,provider,modelId})};
export const host={runtime:(explicit:string)=>invoke<RuntimeInfo>('runtime_status',{explicit:explicit.trim()||null}),list:()=>invoke<TaskSnapshot[]>('list_tasks'),snapshot:(taskId:string)=>invoke<TaskSnapshot>('task_snapshot',{taskId}),prompt:(taskId:string,message:string,attachmentIds:string[]=[])=>invoke<TaskSnapshot>('prompt_task',{taskId,message,attachmentIds}),abort:(taskId:string)=>invoke<TaskSnapshot>('abort_task',{taskId}),stop:(taskId:string)=>invoke<TaskSnapshot>('stop_task',{taskId}),restart:(taskId:string)=>invoke<TaskSnapshot>('restart_task',{taskId}),respond:(taskId:string,requestId:string,value:string|null,confirmed:boolean|null,cancelled:boolean)=>invoke<TaskSnapshot>('respond_ui',{taskId,requestId,value,confirmed,cancelled}),roots:(taskId:string)=>invoke<TaskRoot[]>('task_roots',{taskId}),isolate:(taskId:string)=>invoke<TaskRoot[]>('isolate_task',{taskId}),cleanupWorktrees:(taskId:string)=>invoke<TaskRoot[]>('cleanup_worktrees',{taskId}),recoverWorktrees:(taskId:string)=>invoke<TaskRoot[]>('recover_worktrees',{taskId}),observer:()=>invoke<ObserverInfo>('observer_info')};
export function hostError(e:unknown):HostError{if(typeof e==='object'&&e&&'message'in e){const v=e as any;return{code:v.code||'host_error',message:String(v.message),suggestion:v.suggestion}}return{code:'host_unavailable',message:String(e||'无法连接桌面 Host'),suggestion:'请检查 Host 进程。'}}
export const recoverSession=(taskId:string,confirmed:boolean)=>invoke<string>('recover_session',{taskId,confirmed});
import type {ModelConfig,ModelEdit,ModelCatalog,ModelVerification} from '../../../packages/host-contract/src';
export const modelConfig={apply:()=>invoke<{applied:string[];skipped:string[];errors:{taskId:string;error:HostError}[]}>('model_config_apply'),load:()=>invoke<ModelConfig>('model_config_load'),save:(edit:ModelEdit)=>invoke<ModelConfig>('model_config_save',{edit}),catalog:()=>invoke<ModelCatalog>('model_catalog'),verify:(provider:string|null=null,modelId:string|null=null)=>invoke<ModelVerification>('model_config_verify',{provider,modelId})};

import type {DirectoryPage,FilePreview,Attachment} from '../../../packages/host-contract/src';
export const resources={
 list:(taskId:string,rootIndex:number,path:string)=>invoke<DirectoryPage>('list_task_files',{taskId,rootIndex,path}),
 preview:(taskId:string,rootIndex:number,path:string)=>invoke<FilePreview>('preview_task_file',{taskId,rootIndex,path}),
 attachments:(taskId:string)=>invoke<Attachment[]>('task_attachments',{taskId}),
 import:(taskId:string)=>invoke<Attachment|null>('import_task_attachment',{taskId}),
 previewAttachment:(taskId:string,resourceId:string)=>invoke<FilePreview>('preview_task_attachment',{taskId,resourceId}),
};
