// @vitest-environment jsdom
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {ModelSettings} from './model-settings';
import {modelConfig} from '../../host';
vi.mock('../../host',()=>({modelConfig:{load:vi.fn(),save:vi.fn(),rolesLoad:vi.fn(),rolesSave:vi.fn(),verify:vi.fn(),catalog:vi.fn()},hostError:(e:unknown)=>e}));
const config={path:'/isolated/models.yml',exists:true,revision:'1',providers:[{id:'gateway',baseUrl:'https://example.com/v1',api:'openai-responses',auth:'apiKey',authHeader:null,credentialConfigured:true,models:[{id:'alias',name:'Friendly',originalId:'alias'}]}]};
const roleConfig={path:'/isolated/config.yml',exists:true,revision:'roles-1',roles:{tiny:'legacy/offline:low',commit:null,smol:'gateway/alias'}};
beforeEach(()=>{vi.clearAllMocks();vi.mocked(modelConfig.load).mockResolvedValue(structuredClone(config));vi.mocked(modelConfig.save).mockResolvedValue(structuredClone(config));vi.mocked(modelConfig.rolesLoad).mockResolvedValue(structuredClone(roleConfig));vi.mocked(modelConfig.rolesSave).mockImplementation(async edit=>({...structuredClone(roleConfig),revision:'roles-2',roles:structuredClone(edit.roles)}));vi.mocked(modelConfig.verify).mockResolvedValue({stage:'loaded',message:'配置已加载',models:[{provider:'gateway',id:'alias',name:'Friendly'}]});});afterEach(cleanup);
async function open(){render(<ModelSettings onSaved={vi.fn().mockResolvedValue(undefined)}/>);fireEvent.click(await screen.findByRole('button',{name:'gateway'}));}
it('first use offers provider creation even when model discovery fails',async()=>{vi.mocked(modelConfig.load).mockResolvedValue({path:'/isolated/models.yml',exists:false,revision:'missing',providers:[]});vi.mocked(modelConfig.verify).mockRejectedValue({code:'runtime_missing',message:'OMP 不可用'});render(<ModelSettings onSaved={vi.fn()}/>);fireEvent.click(await screen.findByRole('button',{name:'添加 Provider'}));expect(screen.getByLabelText('Provider ID')).toBeTruthy();expect(await screen.findByText('OMP 不可用')).toBeTruthy();});
it('never echoes an existing key and saves keep semantics with the revision',async()=>{await open();expect(screen.getByText('保留（已配置）')).toBeTruthy();expect(document.querySelector('input[type=password]')).toBeNull();fireEvent.change(screen.getByLabelText('模型 1 显示名称'),{target:{value:'New name'}});fireEvent.click(screen.getByRole('button',{name:'保存配置'}));await waitFor(()=>expect(modelConfig.save).toHaveBeenCalled());expect(vi.mocked(modelConfig.save).mock.calls[0][0]).toMatchObject({revision:'1',credentialAction:'keep',credential:null,provider:{models:[{id:'alias',name:'New name'}]}});await screen.findByText('配置已加载');});
it('retains inputs on save failure',async()=>{vi.mocked(modelConfig.save).mockRejectedValue({code:'config_conflict',message:'外部修改'});await open();await waitFor(()=>expect(modelConfig.verify).toHaveBeenCalledTimes(1));fireEvent.change(screen.getByLabelText('模型 1 请求 ID'),{target:{value:'changed'}});fireEvent.click(screen.getByRole('button',{name:'保存配置'}));await screen.findByText('外部修改');expect((screen.getByLabelText('模型 1 请求 ID') as HTMLInputElement).value).toBe('changed');expect(modelConfig.verify).toHaveBeenCalledTimes(1);});
it('filling preset retains transport ID and separates catalog from connection success',async()=>{vi.mocked(modelConfig.catalog).mockResolvedValue({version:'18.1.15',source:'https://example.com/catalog',cached:true,models:[{provider:'openai',id:'gpt-reference',baseUrl:'https://openai.example',contextWindow:123456,maxTokens:12000,reasoning:true}]});await open();await waitFor(()=>expect(modelConfig.verify).toHaveBeenCalledTimes(1));fireEvent.click(screen.getByText('从预置模型填充参数'));await screen.findByText('openai/gpt-reference');fireEvent.click(screen.getByRole('button',{name:'填充到 alias'}));expect((screen.getByLabelText('模型 1 请求 ID') as HTMLInputElement).value).toBe('alias');expect((screen.getByLabelText('上下文窗口') as HTMLInputElement).value).toBe('123456');expect(modelConfig.verify).toHaveBeenCalledTimes(1);});
it('invalid advanced JSON prevents saving stale valid data',async()=>{await open();fireEvent.change(screen.getByLabelText('Thinking JSON'),{target:{value:'{broken'}});expect((screen.getByRole('button',{name:'保存配置'}) as HTMLButtonElement).disabled).toBe(true);});
it('explains all roles and preserves a configured model that discovery cannot find',async()=>{render(<ModelSettings onSaved={vi.fn()}/>);expect(await screen.findByText('后台轻量任务，例如会话标题、记忆处理、自动思考判断和异常停止处理；不用于主要对话。')).toBeTruthy();expect(screen.getByText('生成 Git 提交信息并更新变更日志。')).toBeTruthy();expect(screen.getByText('快速、低成本的轻量任务和子代理分发。')).toBeTruthy();expect((screen.getByLabelText('Tiny 模型') as HTMLInputElement).value).toBe('legacy/offline:low');expect(await screen.findByText('当前未被 OMP 发现；保存时会保留此值。')).toBeTruthy();});
it('selects, clears, and saves role assignments with their own revision',async()=>{render(<ModelSettings onSaved={vi.fn().mockResolvedValue(undefined)}/>);await screen.findByLabelText('Tiny 模型');fireEvent.change(screen.getByLabelText('Tiny 模型'),{target:{value:'gateway/alias:high'}});fireEvent.click(screen.getByRole('button',{name:'清除 Smol 配置'}));fireEvent.click(screen.getByRole('button',{name:'保存模型用途'}));await waitFor(()=>expect(modelConfig.rolesSave).toHaveBeenCalledWith({revision:'roles-1',roles:{tiny:'gateway/alias:high',commit:null,smol:null}}));expect((screen.getByLabelText('Smol 模型') as HTMLInputElement).value).toBe('');});
it('retains role input when saving roles fails',async()=>{vi.mocked(modelConfig.rolesSave).mockRejectedValue({code:'config_conflict',message:'角色配置已被外部修改'});render(<ModelSettings onSaved={vi.fn()}/>);await screen.findByLabelText('Commit 模型');fireEvent.change(screen.getByLabelText('Commit 模型'),{target:{value:'gateway/commit-model'}});fireEvent.click(screen.getByRole('button',{name:'保存模型用途'}));expect(await screen.findByText('角色配置已被外部修改')).toBeTruthy();expect((screen.getByLabelText('Commit 模型') as HTMLInputElement).value).toBe('gateway/commit-model');});
