import {useEffect,useState} from 'react';
import {Plus,Trash2,RefreshCw,Save,Plug} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {modelConfig,hostError} from '../../host';
import {ErrorNotice} from './shared';
import type {ConfigModel,HostError,ModelCatalog,ModelConfig,ModelProvider,ModelVerification} from '../../../../../packages/host-contract/src';
const apis=['openai-completions','openai-responses','openai-codex-responses','azure-openai-responses','anthropic-messages','bedrock-converse-stream','google-generative-ai','google-gemini-cli','google-vertex'];
const empty=():ModelProvider=>({id:'',baseUrl:'',api:'openai-completions',auth:'apiKey',authHeader:null,credentialConfigured:false,models:[]});
export function ModelSettings({onSaved,onDirtyChange}:{onSaved:()=>Promise<unknown>;onDirtyChange?:(dirty:boolean)=>void}){
 const [config,setConfig]=useState<ModelConfig>(),[provider,setProvider]=useState<ModelProvider>(),[original,setOriginal]=useState<string|null>(null);
 const [credential,setCredential]=useState(''),[action,setAction]=useState<'keep'|'replace'|'clear'>('keep');
 const [catalog,setCatalog]=useState<ModelCatalog>(),[catalogError,setCatalogError]=useState<HostError|null>(null),[query,setQuery]=useState('');
 const [error,setError]=useState<HostError|null>(null),[busy,setBusy]=useState(''),[dirty,setDirty]=useState(false),[verification,setVerification]=useState<ModelVerification>(),[notice,setNotice]=useState(''),[remove,setRemove]=useState(false),[jsonErrors,setJsonErrors]=useState<Record<string,boolean>>({});
 const load=async()=>{setBusy('加载');setError(null);try{setConfig(await modelConfig.load());setProvider(undefined);setDirty(false);setCredential('');}catch(e){setError(hostError(e));}finally{setBusy('');}};
 useEffect(()=>{void load();},[]);
 useEffect(()=>onDirtyChange?.(dirty||!!busy||Object.values(jsonErrors).some(Boolean)),[dirty,busy,jsonErrors,onDirtyChange]);
 const choose=(p:ModelProvider,isNew=false)=>{setProvider(structuredClone(p));setOriginal(isNew?null:p.id);setAction('keep');setCredential('');setDirty(isNew);setVerification(undefined);setNotice('');setRemove(false);setError(null);setJsonErrors({});};
 const update=(patch:Partial<ModelProvider>)=>{setProvider(p=>p?{...p,...patch}:p);setDirty(true);setVerification(undefined);setNotice('');};
 const model=(index:number,patch:Partial<ConfigModel>)=>{if(provider)update({models:provider.models.map((m,i)=>i===index?{...m,...patch}:m)});};
 const save=async(deleted=false)=>{if(!provider||(!deleted&&Object.values(jsonErrors).some(Boolean)))return;setBusy('保存');setError(null);try{const result=await modelConfig.save({revision:config!.revision,originalId:original,provider,credentialAction:action,credential:action==='replace'?credential:null,deleted});setConfig(result);setDirty(false);setCredential('');setAction('keep');setRemove(false);setOriginal(deleted?null:provider.id);setProvider(deleted?undefined:result.providers.find(p=>p.id===provider.id));setNotice('配置已保存。活动任务需重启后应用更改，正在生成的任务不会被中断。');await onSaved();try{setVerification(await modelConfig.verify());}catch(e){setError(hostError(e));}}catch(e){setError(hostError(e));}finally{setBusy('');}};
 const apply=async()=>{setBusy('应用');setError(null);try{const result=await modelConfig.apply();setNotice(`已重载 ${result.applied.length} 个任务；${result.skipped.length} 个任务暂未重载（正在运行或首次回复尚未落盘），稍后可再次应用。`);if(result.errors.length)setError({code:'model_apply_failed',message:`${result.errors.length} 个任务重载失败，请在任务中查看诊断。`});await onSaved();}catch(e){setError(hostError(e));}finally{setBusy('');}};
 const verify=async(id?:string)=>{if(!provider)return;setBusy(id?'连接验证':'加载验证');setError(null);setVerification(undefined);try{setVerification(await modelConfig.verify(id?provider.id:null,id??null));}catch(e){setError(hostError(e));}finally{setBusy('');}};
 const catalogLoad=async()=>{setBusy('预置目录');setCatalogError(null);try{setCatalog(await modelConfig.catalog());}catch(e){setCatalogError(hostError(e));}finally{setBusy('');}};
 const matches=catalog?.models.filter(m=>(m.provider+'/'+m.id+' '+m.name).toLowerCase().includes(query.toLowerCase())).slice(0,60)??[];
 return <section className="model-settings" aria-label="模型配置">
  <div className="model-toolbar model-toolbar-actions"><Button variant="outline" disabled={!!busy||dirty} onClick={()=>void load()}><RefreshCw/>重载</Button></div>
  {config&&<p className="text-xs text-muted-foreground break-all">{config.path}</p>}
  <div className="provider-tabs">{config?.providers.map(p=><Button key={p.id} size="sm" variant={original===p.id?'secondary':'outline'} disabled={!!busy||dirty} onClick={()=>choose(p)}>{p.id}</Button>)}<Button size="sm" variant="outline" disabled={!!busy||dirty||!config} onClick={()=>choose(empty(),true)}><Plus/>添加 Provider</Button></div>
  {config&&!config.providers.length&&!provider&&<p className="model-empty">尚无自定义模型。添加 Provider，填写服务地址、认证与模型 ID 即可开始。</p>}
  {provider&&<fieldset disabled={!!busy} className="space-y-4 min-w-0">
   <div className="model-fields"><Field label="Provider ID"><Input value={provider.id} onChange={e=>update({id:e.target.value})}/></Field><Field label="API 类型"><select value={provider.api??''} onChange={e=>update({api:e.target.value||null})}><option value="">由模型设置</option>{apis.map(a=><option key={a}>{a}</option>)}</select></Field><Field label="基础地址" wide><Input type="url" placeholder="https://api.example.com/v1" value={provider.baseUrl??''} onChange={e=>update({baseUrl:e.target.value||null})}/></Field><Field label="认证方式"><select value={provider.auth??'apiKey'} onChange={e=>update({auth:e.target.value})}><option value="apiKey">API Key</option><option value="none">无需认证</option><option value="oauth">OAuth 请求格式（仍需凭据）</option></select></Field><Field label="认证头"><select value={provider.authHeader===null?'default':String(provider.authHeader)} onChange={e=>update({authHeader:e.target.value==='default'?null:e.target.value==='true'})}><option value="default">OMP 默认</option><option value="true">发送 Bearer 认证头</option><option value="false">不自动发送认证头</option></select></Field></div>
   <div className="model-fields"><Field label="密钥操作"><select value={action} onChange={e=>{setAction(e.target.value as typeof action);setDirty(true);}}><option value="keep">保留{provider.credentialConfigured?'（已配置）':'（未配置）'}</option><option value="replace">替换密钥 / 环境变量</option><option value="clear">清除配置中的密钥</option></select></Field>{action==='replace'&&<Field label="新 API Key 或环境变量名"><Input type="password" autoComplete="new-password" value={credential} onChange={e=>{setCredential(e.target.value);setDirty(true);}}/></Field>}</div>
   <p className="text-xs text-muted-foreground">已有密钥不回显。未知字段与其他 Provider 保留；保存会重新排版 YAML，注释不保留。</p>
   <div className="model-toolbar"><h4>请求模型</h4><Button size="sm" variant="outline" onClick={()=>update({models:[...provider.models,{id:''}]})}><Plus/>添加模型</Button></div>
   {provider.models.map((m,i)=><div className="model-editor" key={i}><div className="model-fields"><Field label={`模型 ${i+1} 请求 ID`}><Input value={m.id} onChange={e=>model(i,{id:e.target.value})}/></Field><Field label={`模型 ${i+1} 显示名称`}><Input value={m.name??''} placeholder="留空使用请求 ID" onChange={e=>model(i,{name:e.target.value||undefined})}/></Field><Field label="上下文窗口"><Input type="number" min={1} value={m.contextWindow??''} placeholder="未设置：由 OMP 继承" onChange={e=>model(i,{contextWindow:e.target.value?Number(e.target.value):undefined})}/></Field><Field label="最大输出 tokens"><Input type="number" min={1} value={m.maxTokens??''} placeholder="未设置：由 OMP 继承" onChange={e=>model(i,{maxTokens:e.target.value?Number(e.target.value):undefined})}/></Field><Field label="推理能力"><select value={m.reasoning===undefined?'default':String(m.reasoning)} onChange={e=>model(i,{reasoning:e.target.value==='default'?undefined:e.target.value==='true'})}><option value="default">未设置：由 OMP 继承</option><option value="true">支持</option><option value="false">不支持</option></select></Field><Field label="输入类型"><select value={m.input?.join(',')??''} onChange={e=>model(i,{input:e.target.value?e.target.value.split(','):undefined})}><option value="">由 OMP 继承</option><option value="text">文本</option><option value="text,image">文本与图片</option></select></Field></div>
    <details><summary>Thinking、价格与模型 API</summary><Field label="模型 API 覆盖"><select value={m.api??''} onChange={e=>model(i,{api:e.target.value||undefined})}><option value="">继承 Provider</option>{apis.map(a=><option key={a}>{a}</option>)}</select></Field><JsonField onInvalid={v=>setJsonErrors(x=>({...x,[i+'thinking']:v}))} label="Thinking JSON" value={m.thinking} onChange={v=>model(i,{thinking:v})}/><JsonField onInvalid={v=>setJsonErrors(x=>({...x,[i+'cost']:v}))} label="价格 JSON（每百万 tokens）" value={m.cost} onChange={v=>model(i,{cost:v})}/></details>
    {catalog&&<p className="text-xs text-muted-foreground">{catalog.models.some(x=>x.id.toLowerCase()===m.id.trim().toLowerCase())?'预置目录存在相同 ID；由 OMP 最终决定参数继承。':'目录无精确 ID；可手动选择参考参数。OMP 可能另有别名匹配。'}</p>}
    <div className="model-toolbar"><Button size="sm" variant="outline" disabled={dirty||!original} onClick={()=>void verify(m.id)}><Plug/>验证连接（会产生调用）</Button><Button variant="ghost" size="sm" className="text-destructive" onClick={()=>{update({models:provider.models.filter((_,n)=>n!==i)});setJsonErrors({});}}><Trash2/>移除模型</Button></div>
   </div>)}
   <details className="catalog-section"><summary onClick={()=>{if(!catalog&&!busy)void catalogLoad();}}>从预置模型填充参数</summary><p className="text-xs text-muted-foreground">按请求 ID 查找，填充不会更改你的请求 ID 或服务地址。参考限额不等于网关实际限额。推理与 thinking 是配置元数据，不代表当前服务支持；工作台以 OMP 实时发现为准。</p><ErrorNotice error={catalogError}/>{catalog&&<><p className="text-xs">OMP {catalog.version} · {catalog.cached?'版本缓存':'官方版本目录'} · {catalog.models.length} 个条目</p><code className="block break-all text-xs">{catalog.source}</code><Input aria-label="搜索预置模型" placeholder="搜索 Provider / 模型 ID" value={query} onChange={e=>setQuery(e.target.value)}/><div className="catalog-results">{matches.map((entry,i)=><details key={entry.provider+'/'+entry.id+i}><summary>{entry.provider}/{entry.id}</summary><pre>{JSON.stringify({contextWindow:entry.contextWindow,maxTokens:entry.maxTokens,reasoning:entry.reasoning,thinking:entry.thinking,input:entry.input,cost:entry.cost},null,2)}</pre>{provider.models.map((m,index)=><Button key={index} variant="outline" size="sm" className="m-1" onClick={()=>{const {id:_,name:__,provider:___,baseUrl:____,api:_____,...params}=entry;model(index,params);}}>填充到 {m.id||`模型 ${index+1}`}</Button>)}</details>)}{!matches.length&&<p>没有匹配条目</p>}</div></>}</details>
   <div className="model-toolbar"><div className="flex gap-2"><Button onClick={()=>void save()} disabled={!dirty||Object.values(jsonErrors).some(Boolean)}><Save/>保存配置</Button><Button variant="outline" disabled={dirty} onClick={()=>void verify()}>验证加载</Button>{dirty&&<Button variant="ghost" onClick={()=>{if(original){const p=config?.providers.find(p=>p.id===original);if(p)choose(p);}else{setProvider(undefined);setDirty(false);setCredential('');}}}>放弃修改</Button>}</div>{original&&<Button variant="ghost" className="text-destructive" onClick={()=>setRemove(true)}>删除 Provider</Button>}</div>
   {remove&&<div role="alert" className="model-delete"><p>删除 {original} 及其模型配置？此操作不会删除 OMP 会话。</p><Button variant="destructive" onClick={()=>void save(true)}>确认删除</Button><Button variant="outline" onClick={()=>setRemove(false)}>保留</Button></div>}
  </fieldset>}
  {busy&&<p role="status">{busy}中…</p>}{notice&&<div><p role="status" className="text-xs">{notice}</p><Button className="mt-2" variant="outline" disabled={!!busy||dirty} onClick={()=>void apply()}>重载空闲任务并刷新模型</Button></div>}{verification&&<div role="status" className="runtime-result"><strong>{verification.message}</strong><p>{verification.models.length} 个可用模型{provider&&' · 当前 Provider '+verification.models.filter(m=>m.provider===provider.id).length+' 个'}</p></div>}<ErrorNotice error={error}/>
 </section>;
}
function Field({label,wide,children}:{label:string;wide?:boolean;children:React.ReactElement}){return <label className={wide?'model-field model-wide':'model-field'}><span>{label}</span>{children}</label>;}
function JsonField({label,value,onChange,onInvalid}:{onInvalid:(v:boolean)=>void;label:string;value?:Record<string,unknown>;onChange:(v:Record<string,unknown>|undefined)=>void}){const [text,setText]=useState(value?JSON.stringify(value,null,2):''),[error,setError]=useState('');useEffect(()=>setText(value?JSON.stringify(value,null,2):''),[value]);return <Field label={label}><div><Textarea aria-label={label} value={text} onChange={e=>{setText(e.target.value);try{const v=e.target.value.trim()?JSON.parse(e.target.value):undefined;if(v!==undefined&&(!v||typeof v!=='object'||Array.isArray(v)))throw Error();onChange(v);onInvalid(false);setError('');}catch{onInvalid(true);setError('请输入有效 JSON 对象；无效内容不会提交');}}}/>{error&&<p role="alert">{error}</p>}</div></Field>;}
