// @vitest-environment jsdom
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {ModelSettings} from './model-settings';
import {modelConfig} from '../../host';
vi.mock('../../host',()=>({modelConfig:{load:vi.fn(),save:vi.fn(),verify:vi.fn(),catalog:vi.fn()},hostError:(e:unknown)=>e}));
const config={path:'/isolated/models.yml',exists:true,revision:'1',providers:[{id:'gateway',baseUrl:'https://example.com/v1',api:'openai-responses',auth:'apiKey',authHeader:null,credentialConfigured:true,models:[{id:'alias',name:'Friendly',originalId:'alias'}]}]};
beforeEach(()=>{vi.clearAllMocks();vi.mocked(modelConfig.load).mockResolvedValue(structuredClone(config));vi.mocked(modelConfig.save).mockResolvedValue(structuredClone(config));vi.mocked(modelConfig.verify).mockResolvedValue({stage:'loaded',message:'配置已加载',models:[]});});afterEach(cleanup);
async function open(){render(<ModelSettings onSaved={vi.fn().mockResolvedValue(undefined)}/>);fireEvent.click(await screen.findByRole('button',{name:'gateway'}));}
it('first use offers provider creation independent of RPC',async()=>{vi.mocked(modelConfig.load).mockResolvedValue({path:'/isolated/models.yml',exists:false,revision:'missing',providers:[]});render(<ModelSettings onSaved={vi.fn()}/>);fireEvent.click(await screen.findByRole('button',{name:'添加 Provider'}));expect(screen.getByLabelText('Provider ID')).toBeTruthy();expect(modelConfig.verify).not.toHaveBeenCalled();});
it('never echoes an existing key and saves keep semantics with the revision',async()=>{await open();expect(screen.getByText('保留（已配置）')).toBeTruthy();expect(document.querySelector('input[type=password]')).toBeNull();fireEvent.change(screen.getByLabelText('模型 1 显示名称'),{target:{value:'New name'}});fireEvent.click(screen.getByRole('button',{name:'保存配置'}));await waitFor(()=>expect(modelConfig.save).toHaveBeenCalled());expect(vi.mocked(modelConfig.save).mock.calls[0][0]).toMatchObject({revision:'1',credentialAction:'keep',credential:null,provider:{models:[{id:'alias',name:'New name'}]}});await screen.findByText('配置已加载');});
it('retains inputs on save failure',async()=>{vi.mocked(modelConfig.save).mockRejectedValue({code:'config_conflict',message:'外部修改'});await open();fireEvent.change(screen.getByLabelText('模型 1 请求 ID'),{target:{value:'changed'}});fireEvent.click(screen.getByRole('button',{name:'保存配置'}));await screen.findByText('外部修改');expect((screen.getByLabelText('模型 1 请求 ID') as HTMLInputElement).value).toBe('changed');expect(modelConfig.verify).not.toHaveBeenCalled();});
it('filling preset retains transport ID and separates catalog from connection success',async()=>{vi.mocked(modelConfig.catalog).mockResolvedValue({version:'18.1.15',source:'https://example.com/catalog',cached:true,models:[{provider:'openai',id:'gpt-reference',baseUrl:'https://openai.example',contextWindow:123456,maxTokens:12000,reasoning:true}]});await open();fireEvent.click(screen.getByText('从预置模型填充参数'));await screen.findByText('openai/gpt-reference');fireEvent.click(screen.getByRole('button',{name:'填充到 alias'}));expect((screen.getByLabelText('模型 1 请求 ID') as HTMLInputElement).value).toBe('alias');expect((screen.getByLabelText('上下文窗口') as HTMLInputElement).value).toBe('123456');expect(modelConfig.verify).not.toHaveBeenCalled();});
it('invalid advanced JSON prevents saving stale valid data',async()=>{await open();fireEvent.change(screen.getByLabelText('Thinking JSON'),{target:{value:'{broken'}});expect((screen.getByRole('button',{name:'保存配置'}) as HTMLButtonElement).disabled).toBe(true);});
