import {RuntimeManagement} from './runtime-management';
import {ModelSettings} from './model-settings';
import {TitlePromptSettings} from './title-prompt-settings';
import {AgentsSettings} from './agents-settings';
import {PluginSettings,ProviderSettings} from './ecosystem-settings';
import {useRef,useState} from 'react';
import {Check,Copy,FolderOpen,Monitor,Sun,Moon,Search,LoaderCircle,GitBranch,Users,Sparkles} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {host,hostError,records,recoverSession} from '../../host';
import {ErrorNotice} from './shared';
import type {HostError,Project,RuntimeInfo,RuntimeTaskInfo,TaskRecord} from '../../../../../packages/host-contract/src';
import type {Theme} from './theme';
import type {UiPreferences} from './preferences';

export function NameDialog({kind,initial,onClose,onSubmit,onGenerate,restoreFocus}:{kind:'project'|'task'|'rename';initial:string;onClose:()=>void;onSubmit:(name:string,trusted:boolean,mode:'shared'|'isolated')=>Promise<void>;onGenerate?:()=>Promise<string>;restoreFocus:()=>void}){
 const input=useRef<HTMLInputElement>(null);
 const [value,setValue]=useState(initial),[trusted,setTrusted]=useState(false),[mode,setMode]=useState<'shared'|'isolated'>('shared'),[busy,setBusy]=useState(false),[error,setError]=useState<HostError|null>(null);
 const [candidate,setCandidate]=useState(''),[generating,setGenerating]=useState(false),[generateError,setGenerateError]=useState<HostError|null>(null);
 const title=kind==='project'?'添加项目':kind==='task'?'创建任务':'重命名';
 return <Dialog open onOpenChange={v=>{if(!v&&!busy)onClose();}}><DialogContent onCloseAutoFocus={e=>{e.preventDefault();restoreFocus();}}><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{kind==='project'?'通过系统目录选择器登记主目录及附加目录。第一项为主目录。':kind==='task'?'任务保留自己的会话和目录快照，创建后不会自动启动 OMP。':'修改显示名称，不改变任务或会话身份。'}</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();if(!value.trim()){setError({code:'invalid_name',message:'请输入名称'});return;}setBusy(true);setError(null);void onSubmit(value.trim(),trusted,mode).then(onClose).catch(e=>setError(hostError(e))).finally(()=>setBusy(false));}}>
  <Label htmlFor="name-field">名称</Label><Input ref={input} id="name-field" autoFocus value={value} onChange={e=>setValue(e.target.value)} maxLength={160} aria-invalid={!!error} className="mt-2"/>
  {onGenerate&&<div className="mt-3 space-y-3 border-t pt-3"><Button type="button" size="sm" variant="outline" disabled={busy||generating} onClick={()=>{if(generating)return;setGenerating(true);setCandidate('');setGenerateError(null);void onGenerate().then(title=>setCandidate(title)).catch(e=>setGenerateError(hostError(e))).finally(()=>setGenerating(false));}}>{generating?<LoaderCircle className="animate-spin"/>:<Sparkles/>}{generating?'生成中':'自动生成'}</Button>{candidate&&<div className="flex items-center justify-between gap-3 rounded-md border bg-muted/30 px-3 py-2" role="status"><span className="min-w-0 break-words text-sm">{candidate}</span><Button type="button" size="sm" variant="secondary" disabled={busy} onClick={()=>{setValue(candidate);requestAnimationFrame(()=>input.current?.focus());}}><Check/>应用</Button></div>}<ErrorNotice error={generateError}/></div>}
  {kind==='project'&&<label className="trust-label"><Checkbox checked={trusted} onCheckedChange={v=>setTrusted(v===true)}/><span>我信任所选目录中的配置与扩展，允许 OMP 加载它们。</span></label>}
  {kind==='task'&&<div className="space-y-2"><Label>执行目录</Label><div className="flex gap-2"><Button type="button" variant={mode==='shared'?'secondary':'outline'} onClick={()=>setMode('shared')}><Users/>共享目录</Button><Button type="button" variant={mode==='isolated'?'secondary':'outline'} onClick={()=>setMode('isolated')}><GitBranch/>隔离 worktree</Button></div>{mode==='isolated'&&<p className="text-xs text-muted-foreground">仅支持 Git 根目录。同一仓库会共用一个 worktree；未提交改动不包含在新任务中。</p>}</div>}
  <ErrorNotice error={error}/><DialogFooter className="mt-5"><Button type="button" variant="outline" disabled={busy} onClick={onClose}>取消</Button><Button disabled={busy||!value.trim()||kind==='project'&&!trusted}>{busy?<LoaderCircle className="animate-spin"/>:kind==='project'?<FolderOpen/>:null}{kind==='project'?'选择目录':busy?'保存中':'保存'}</Button></DialogFooter>
 </form></DialogContent></Dialog>;
}

export type SettingsTab='general'|'appearance'|'models'|'providers'|'skills'|'agents'|'plugins'|'runtime';

export function RuntimeSettings({tab,onTab:setTab,runtimeTasks,tasks,projects,projectId,taskId,runtimeError,onRefreshRuntime,onOpenTask,onProviderLogin,open,onClose,theme,onTheme,themeError,preferences,onPreferences,preferencesError,restoreFocus,onSaved}: {tab:SettingsTab;onTab:(tab:SettingsTab)=>void;runtimeTasks:RuntimeTaskInfo[];tasks:TaskRecord[];projects:Project[];projectId:string;taskId?:string;runtimeError:HostError|null;onRefreshRuntime:()=>Promise<void>;onOpenTask:(task:TaskRecord)=>void;onProviderLogin:()=>void;open:boolean;onClose:()=>void;theme:Theme;onTheme:(t:Theme)=>void;themeError:string;preferences:UiPreferences;onPreferences:(patch:Partial<UiPreferences>)=>void;preferencesError:string;restoreFocus:()=>void;onSaved:()=>Promise<unknown>}){
 const [modelDirty,setModelDirty]=useState(false),[agentsDirty,setAgentsDirty]=useState(false),[titleDirty,setTitleDirty]=useState(false),[confirmClose,setConfirmClose]=useState(false);
 const settingsDirty=modelDirty||agentsDirty||titleDirty;
 const [path,setPath]=useState(''),[runtime,setRuntime]=useState<RuntimeInfo>(),[busy,setBusy]=useState(false),[discovering,setDiscovering]=useState(false),[error,setError]=useState<HostError|null>(null);
 const inspect=async(candidate:string)=>{setBusy(true);setError(null);try{setRuntime(await host.runtime(candidate));}catch(e){setError(hostError(e));}finally{setBusy(false);}};
 const chooseRuntime=async()=>{setDiscovering(true);setError(null);try{const candidate=await host.chooseRuntime();if(candidate){setPath(candidate);await inspect(candidate);}}catch(e){setError(hostError(e));}finally{setDiscovering(false);}};
 const discoverRuntime=async()=>{setDiscovering(true);setError(null);try{const candidate=await host.discoverRuntime();if(!candidate){setError({code:'not_found',message:'登录 Shell 中也未找到 OMP',suggestion:'请使用“选择 OMP”指定绝对路径。'});return;}setPath(candidate);await inspect(candidate);}catch(e){setError(hostError(e));}finally{setDiscovering(false);}};
 return <Dialog open={open} onOpenChange={v=>{if(!v){if(settingsDirty)setConfirmClose(true);else onClose();}}}><DialogContent className="settings-dialog" onCloseAutoFocus={e=>{e.preventDefault();restoreFocus();}}><DialogHeader><DialogTitle>设置</DialogTitle><DialogDescription>配置工作台偏好与 OMP 运行时。</DialogDescription></DialogHeader>
  {confirmClose&&<div role="alert"><p>有未保存的修改或操作正在执行。完成操作后再关闭，或明确放弃当前输入。</p><Button variant="outline" onClick={()=>setConfirmClose(false)}>继续编辑</Button><Button variant="destructive" onClick={()=>{setConfirmClose(false);setModelDirty(false);setAgentsDirty(false);setTitleDirty(false);onClose();}}>放弃输入并关闭</Button></div>}
  <div className="settings-navigation"><Button aria-pressed={tab==='general'} variant={tab==='general'?'secondary':'ghost'} onClick={()=>setTab('general')}>常规</Button><Button aria-pressed={tab==='appearance'} variant={tab==='appearance'?'secondary':'ghost'} onClick={()=>setTab('appearance')}>外观</Button><Button aria-pressed={tab==='models'} variant={tab==='models'?'secondary':'ghost'} onClick={()=>setTab('models')}>模型</Button><Button aria-pressed={tab==='providers'} variant={tab==='providers'?'secondary':'ghost'} onClick={()=>setTab('providers')}>Provider</Button><Button aria-pressed={tab==='skills'} variant={tab==='skills'?'secondary':'ghost'} onClick={()=>setTab('skills')}>Skills</Button><Button aria-pressed={tab==='agents'} variant={tab==='agents'?'secondary':'ghost'} onClick={()=>setTab('agents')}>Agents</Button><Button aria-pressed={tab==='plugins'} variant={tab==='plugins'?'secondary':'ghost'} onClick={()=>setTab('plugins')}>Plugins</Button><Button aria-pressed={tab==='runtime'} variant={tab==='runtime'?'secondary':'ghost'} onClick={()=>setTab('runtime')}>Runtime</Button></div>
  <div className="settings-body" hidden={tab!=='general'}><h2>常规</h2><p className="settings-intro">配置会话标题等工作台默认行为。</p>{open&&<TitlePromptSettings onDirtyChange={setTitleDirty}/>}</div>
  <div className="settings-body" hidden={tab!=='models'}><h2>模型配置</h2><p className="settings-intro">连接你的模型，开始工作。</p>{open&&<ModelSettings onSaved={onSaved} onDirtyChange={setModelDirty}/>}</div><div className="settings-body" hidden={tab!=='appearance'}><h2>外观与偏好</h2><p className="settings-intro">调整工作台阅读密度和完成提醒。</p>
  <section className="settings-section settings-section-plain" aria-label="外观主题"><h3>主题</h3><div className="theme-options">{([['light','浅色',Sun],['dark','深色',Moon],['system','跟随系统',Monitor]] as const).map(([value,label,Icon])=><Button key={value} variant={theme===value?'secondary':'outline'} aria-pressed={theme===value} onClick={()=>onTheme(value)}><Icon/>{label}</Button>)}</div>{themeError&&<p role="alert">{themeError}</p>}</section>
  <section className="settings-section settings-section-plain preference-grid" aria-label="阅读偏好"><label>会话宽度<select value={preferences.chatWidth} onChange={event=>onPreferences({chatWidth:event.target.value as UiPreferences['chatWidth']})}><option value="compact">紧凑 · 680px</option><option value="standard">标准 · 800px</option><option value="wide">宽 · 960px</option></select></label><label>正文字号<select value={preferences.fontSize} onChange={event=>onPreferences({fontSize:event.target.value as UiPreferences['fontSize']})}><option value="compact">紧凑 · 13px</option><option value="standard">标准 · 14px</option><option value="large">大 · 15px</option></select></label><label>代码主题<select value={preferences.codeTheme} onChange={event=>onPreferences({codeTheme:event.target.value as UiPreferences['codeTheme']})}><option value="adaptive">跟随工作台</option><option value="github">GitHub Light</option><option value="monokai">Monokai</option></select></label><label className="preference-toggle"><Checkbox checked={preferences.thinkingExpanded} onCheckedChange={value=>onPreferences({thinkingExpanded:value===true})}/>默认展开 Thinking</label><label className="preference-toggle"><Checkbox checked={preferences.notifications} onCheckedChange={value=>onPreferences({notifications:value===true})}/>任务完成时显示系统通知</label><label className="preference-toggle"><Checkbox checked={preferences.sound} onCheckedChange={value=>onPreferences({sound:value===true})}/>任务完成时播放提示音</label></section>{preferencesError&&<p role="alert">{preferencesError}</p>}
  </div>
  <div className="settings-body" hidden={tab!=='providers'}><h2>Provider</h2><p className="settings-intro">通过 OMP 官方 RPC 登录，并查看脱敏后的账号用量。</p>{open&&<ProviderSettings taskId={taskId} onLoginStarted={onProviderLogin}/>}</div>
  <div className="settings-body" hidden={tab!=='skills'}><h2>Skills</h2><p className="settings-intro">OMP 当前没有独立的 Skills 管理 CLI 或 RPC。</p><section className="settings-section settings-section-plain"><p className="settings-empty">为避免直接改写 OMP 内部文件语义，发现、启停、安装与更新保持不可用。已安装 Skill 仍由 OMP 在任务启动时加载。</p></section></div>
  <div className="settings-body" hidden={tab!=='agents'}><h2>Agent Profiles</h2><p className="settings-intro">用户级 Profile 被项目级同名 Profile 覆盖；保存时保留完整 Markdown 与未知字段。</p>{open&&<AgentsSettings projects={projects} projectId={projectId} onDirtyChange={setAgentsDirty}/>}</div>
  <div className="settings-body" hidden={tab!=='plugins'}><h2>Plugins</h2><p className="settings-intro">读取 OMP 官方插件清单和 doctor 结果；启用与禁用使用结构化参数。</p>{open&&<PluginSettings projects={projects} projectId={projectId}/>}</div>
  <div className="settings-body" hidden={tab!=='runtime'}><h2>运行管理</h2><p className="settings-intro">查看本机 OMP 状态，管理所有任务的运行进程。</p><RuntimeManagement all={runtimeTasks} tasks={tasks} error={runtimeError} onRefresh={onRefreshRuntime} onOpenTask={settingsDirty?undefined:onOpenTask}/>{settingsDirty&&<p className="inspector-note">设置中有未保存的修改或操作正在执行，完成后可跳转任务。</p>}
  <section className="settings-section"><h3>OMP 运行时</h3><p className="text-muted-foreground text-xs mb-4">使用本机已安装的 OMP。检测会短暂启动探测进程，不运行任务。</p><Label htmlFor="runtime-path">可执行文件路径</Label><Input id="runtime-path" value={path} onChange={e=>setPath(e.target.value)} placeholder="留空使用已保存路径或 PATH" className="my-2 font-mono text-xs"/><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy||discovering} onClick={()=>void inspect(path)}>{busy?<LoaderCircle className="animate-spin"/>:<Search/>}{busy?'检测中':'检测 OMP'}</Button><Button variant="outline" disabled={busy||discovering} onClick={()=>void chooseRuntime()}>{discovering?<LoaderCircle className="animate-spin"/>:<FolderOpen/>}{discovering?'查找中':'选择 OMP'}</Button><Button variant="ghost" disabled={busy||discovering} onClick={()=>void discoverRuntime()}><Search/>{discovering?'查找中':'从登录 Shell 查找'}</Button></div>
  {runtime&&<div className="runtime-result"><p>{runtime.status} · {runtime.version??'未知版本'} · RPC {runtime.protocol??'—'}</p><code className="break-all text-xs">{runtime.executable}</code><ErrorNotice error={runtime.error}/></div>}<ErrorNotice error={error}/></section>
  </div>
 </DialogContent></Dialog>;
}

export function RecoveryDialog({task,roots,onClose,onChanged,restoreFocus}:{task?:TaskRecord;roots:string[];onClose:()=>void;onChanged:()=>Promise<unknown>;restoreFocus:()=>void}){
 const [trusted,setTrusted]=useState(false),[candidate,setCandidate]=useState(''),[error,setError]=useState<HostError|null>(null),[busy,setBusy]=useState(false),[copied,setCopied]=useState('');
 const action=async(f:()=>Promise<unknown>)=>{setBusy(true);setError(null);try{await f();await onChanged();}catch(e){setError(hostError(e));}finally{setBusy(false);}};
 return <Dialog open onOpenChange={v=>{if(!v&&!busy)onClose();}}><DialogContent className="sm:max-w-xl" onCloseAutoFocus={e=>{e.preventDefault();restoreFocus();}}><DialogHeader><DialogTitle>{task?'目录与会话恢复':'项目目录'}</DialogTitle><DialogDescription>主目录决定 OMP 工作位置。附加目录保持独立，不代表隔离沙箱。</DialogDescription></DialogHeader>
  <div className="space-y-3">{roots.map((root,i)=><div key={root} className="root-path"><span>{i===0?'主目录':`附加目录 ${i}`}</span><code>{root}</code><Button size="icon-sm" variant="ghost" aria-label={`复制${i===0?'主目录':'附加目录 '+i}`} onClick={()=>void navigator.clipboard.writeText(root).then(()=>setCopied(root)).catch(e=>setError(hostError(e)))}><Copy/></Button>{copied===root&&<small role="status">已复制</small>}</div>)}</div>
  {task&&<><Label className="trust-label"><Checkbox checked={trusted} onCheckedChange={v=>setTrusted(v===true)}/>信任重新选择的目录及其配置</Label><Button variant="outline" disabled={busy||!trusted} onClick={()=>void action(async()=>{await records.relocate(task.id,trusted);setTrusted(false);})}><FolderOpen/>重新定位目录</Button><p className="text-xs text-muted-foreground">需要先停止任务。会话和任务记录不会被删除。</p><div className="border-t pt-4"><p className="text-xs break-all text-muted-foreground">会话：{task.sessionId??'尚未绑定'}</p>{!task.sessionId&&<Button className="mt-3" variant="outline" disabled={busy} onClick={()=>void action(async()=>setCandidate(await recoverSession(task.id,false)))}>查找未绑定会话</Button>}{candidate&&<div className="mt-3"><p className="text-xs break-all">唯一候选：{candidate}</p><Button disabled={busy} className="mt-2" onClick={()=>void action(async()=>{await recoverSession(task.id,true);setCandidate('');})}>确认恢复此会话</Button></div>}</div></>}
  <ErrorNotice error={error}/>
 </DialogContent></Dialog>;
}
